title: "Portfolio-Data-Analyst-Buisness-analyst-"
logo: <img src="Image.jpg" width="150" style="border-radius: 50%;" />
description: "Portfolio Data Scientist - IA, Data Science, Formation"
show_dowloads: true
theme: jekyll-theme-minimal
lang: fr
